// DropdownComponent.jsx
import { useState } from 'react';

// List of entities with names and abbreviations
const entities = [
  { name: "ABC Water Utility Authority", abbr: "ABC" },
  { name: "ABQ", abbr: "ABQ" },
  { name: "ADC", abbr: "ADC" },
  { name: "AMAFCA", abbr: "AMA" },
  { name: "American Water", abbr: "AW" },
  { name: "Animas River Irrigation Company", abbr: "ARIC" },
  { name: "APS", abbr: "APS" },
  { name: "Arizona Co.", abbr: "AZCO" },
  { name: "Atmos Energy", abbr: "ATMS" },
  { name: "Belen", abbr: "BEL" },
  { name: "Benchland Water District", abbr: "BWD" },
  { name: "Big Hills Corporation", abbr: "BHC" },
  { name: "Bluefield WSD 500", abbr: "BWSD" },
  { name: "Bonita Water Improvement", abbr: "BWI" },
  { name: "Boulder City", abbr: "BC" },
  { name: "Brighton Landscaping", abbr: "BL" },
  { name: "CC Communications", abbr: "CCOM" },
  { name: "Cedar City", abbr: "CC" },
  { name: "CenterPoint Energy", abbr: "CPE" },
  { name: "Central Public Works", abbr: "CPW" },
  { name: "Central Utah Water District", abbr: "CUWD" },
  { name: "CenturyLink", abbr: "CTL" },
  { name: "Gila River Indian Community", abbr: "GIL" },
  { name: "Charter", abbr: "CHAR" },
  { name: "Cheyenne Light Power & Fuel", abbr: "CLPF" },
  { name: "City of Albuquerque", abbr: "ABQ" },
  { name: "City of Aurora", abbr: "AUR" },
  { name: "City of Elbert", abbr: "ELB" },
  { name: "City of Glenwood Springs", abbr: "GWS" },
  { name: "City of Greeley", abbr: "GREE" },
  { name: "City of Las Vegas", abbr: "LV" },
  { name: "City of Littleton", abbr: "LITT" },
  { name: "City of Pueblo", abbr: "PUE" },
  { name: "City of Roswell", abbr: "ROS" },
  { name: "City of Sparks", abbr: "SPKS" },
  { name: "City of St. George", abbr: "STG" },
  { name: "Clearfield Irrigation", abbr: "CLFI" },
  { name: "City of Winnemucca", abbr: "WNM" },
  { name: "Cogent Communications", abbr: "COG" },
  { name: "Comcast", abbr: "COM" },
  { name: "Cottonwood Heights City", abbr: "CHC" },
  { name: "Crawford Properties", abbr: "CP" },
  { name: "Crown Castle", abbr: "CC" },
  { name: "Cub River Irrigation", abbr: "CRI" },
  { name: "Daybreak Secondary Water", abbr: "DSW" },
  { name: "Davis County", abbr: "DC" },
  { name: "Denver Water", abbr: "DW" },
  { name: "Desert Mound", abbr: "DM" },
  { name: "Dixie Power", abbr: "DP" },
  { name: "Dominion", abbr: "DOM" },
  { name: "Douglas County School District", abbr: "DCSD" },
  { name: "Draper City Public Works", abbr: "DCPW" },
  { name: "ECIV", abbr: "ECIV" },
  { name: "Edgewood Water Company", abbr: "EWC" },
  { name: "Elevation Field Services", abbr: "EFS" },
  { name: "Elk Petroleum", abbr: "ELK" },
  { name: "Embridge Utah", abbr: "EU" },
  { name: "Enterprise", abbr: "ENT" },
  { name: "Estes Park", abbr: "EP" },
  { name: "Expansion & Ops", abbr: "EXO" },
  { name: "Farmington City", abbr: "FC" },
  { name: "Federal Telecom", abbr: "FT" },
  { name: "Fort Collins", abbr: "FC" },
  { name: "Garuda Energy Cooperative", abbr: "GEC" },
  { name: "Gila Water Co-op", abbr: "GWC" },
  { name: "Granger-Hunter Improvement District", abbr: "GHID" },
  { name: "Green River Irrigation", abbr: "GRI" },
  { name: "HAFT", abbr: "HAFT" },
  { name: "Highlands Ranch District 1", abbr: "HRD1" },
  { name: "Highland Metro District", abbr: "HMD" },
  { name: "Hill Air Force Base", abbr: "HAFB" },
  { name: "Holladay", abbr: "HOL" },
  { name: "Holy Cross Energy", abbr: "HCE" },
  { name: "Hooper Water Improvement District", abbr: "HWID" },
  { name: "Impact", abbr: "IMP" },
  { name: "Inwoven", abbr: "INW" },
  { name: "Jordan and Salt Lake City Canal", abbr: "JSLC" },
  { name: "JUBCO", abbr: "JUB" },
  { name: "K.P. Kaufman Company", abbr: "KPC" },
  { name: "Kacy", abbr: "KAC" },
  { name: "Kemmerer", abbr: "KEM" },
  { name: "Kinder Morgan", abbr: "KM" },
  { name: "Las Vegas Valley Water District", abbr: "LVVWD" },
  { name: "Layton City", abbr: "LC" },
  { name: "Lehi City Water", abbr: "LCW" },
  { name: "Leavittson Cities", abbr: "LEAV" },
  { name: "Lind", abbr: "LIN" },
  { name: "Little Thompson Water District", abbr: "LTWD" },
  { name: "Logan River District", abbr: "LRD" },
  { name: "Magna Water", abbr: "MW" },
  { name: "Marathon Pipeline", abbr: "MP" },
  { name: "McHenry Company", abbr: "MCH" },
  { name: "Metropolitan Water District of SLC", abbr: "MWDS" },
  { name: "Middle Telephone", abbr: "MTEL" },
  { name: "Minden-Gardnerville Sanitation District", abbr: "MGSD" },
  { name: "Mountain View Recreation", abbr: "MVR" },
  { name: "Mt. Olympus Improvement District", abbr: "MOID" },
  { name: "Murray City, Power, Storm Water", abbr: "MCPSW" },
  { name: "New Mexico Gas Company", abbr: "NMGC" },
  { name: "North Salt Lake City", abbr: "NSLC" },
  { name: "North Tooele Fire District", abbr: "NTFD" },
  { name: "NV Energy", abbr: "NVE" },
  { name: "Onsite", abbr: "ONS" },
  { name: "Otero Electric", abbr: "OE" },
  { name: "Oro Valley", abbr: "OV" },
  { name: "Palisade Irrigation", abbr: "PI" },
  { name: "Paradise LLC", abbr: "PARA" },
  { name: "Parker Water & Sanitation", abbr: "PWS" },
  { name: "Peak City", abbr: "PC" },
  { name: "Perry City", abbr: "PER" },
  { name: "Pima", abbr: "PIM" },
  { name: "Pioneer", abbr: "PIO" },
  { name: "Power", abbr: "POW" },
  { name: "Pueblo Rural Electric", abbr: "PRE" },
  { name: "Pueblo Water", abbr: "PW" },
  { name: "Qwest", abbr: "QWE" },
  { name: "Radio One (ISP)", abbr: "ROE" },
  { name: "Riverton City", abbr: "RC" },
  { name: "Riverton Power", abbr: "RP" },
  { name: "Rocky Ground", abbr: "RG" },
  { name: "Rocky Tower Improvement District", abbr: "RTID" },
  { name: "Roy", abbr: "ROY" },
  { name: "Ryan Conservation District", abbr: "RCD" },
  { name: "SUE Flood Operations", abbr: "SFO" },
  { name: "Sandy City Department Public Utilities", abbr: "SCDPU" },
  { name: "Santaquin City", abbr: "SAN" },
  { name: "Saratoga", abbr: "SAR" },
  { name: "Signal West LLC", abbr: "SWL" },
  { name: "Southeast Metro Stormwater Authority", abbr: "SEMSA" },
  { name: "South Davis Sewer District", abbr: "SDSD" },
  { name: "South Lake Tahoe", abbr: "SLT" },
  { name: "South Weber", abbr: "SW" },
  { name: "Southwest Irrigation", abbr: "SWI" },
  { name: "Southwest Gas", abbr: "SWG" },
  { name: "Sparklight", abbr: "SPKL" },
  { name: "Spring City Irrigation", abbr: "SCI" },
  { name: "Springville City", abbr: "SC" },
  { name: "Stansbury Park Improvement District", abbr: "SPID" },
  { name: "St. George", abbr: "STG" },
  { name: "Strawberry", abbr: "STR" },
  { name: "Sulphur Springs Valley Electric Co-op", abbr: "SSVEC" },
  { name: "Sunset City", abbr: "SUNC" },
  { name: "SVIPS", abbr: "SVIP" },
  { name: "Syracuse", abbr: "SYR" },
  { name: "Taylor Weber Water", abbr: "TWW" },
  { name: "Taylorsville-Bennion Improvement District", abbr: "TBID" },
  { name: "Telecom Communications America", abbr: "TCA" },
  { name: "T-Mobile Special", abbr: "TMS" },
  { name: "Town of Alta", abbr: "TOA" },
  { name: "Town of Gardnerville", abbr: "TOG" },
  { name: "Town of Mesquite", abbr: "TOM" },
  { name: "Town of Meadows Water Authority", abbr: "TMWA" },
  { name: "Tucson", abbr: "TUC" },
  { name: "U.S. Bureau of Reclamation", abbr: "USBR" },
  { name: "Uintah Mountain Stream Irrigation Co.", abbr: "UMSI" },
  { name: "Uintahfield Inc.", abbr: "UINT" },
  { name: "United Power", abbr: "UP" },
  { name: "Upper River", abbr: "UR" },
  { name: "Utah Authority", abbr: "UA" },
  { name: "Utah Telecom", abbr: "UT" },
  { name: "Valle Telephone Co-op", abbr: "VTC" },
  { name: "Vernal City", abbr: "VC" },
  { name: "Virgin City", abbr: "VIR" },
  { name: "Wasatch", abbr: "WAS" },
  { name: "Water Pro Inc.", abbr: "WPI" },
  { name: "Weber County", abbr: "WC" },
  { name: "Weber-Box Elder Conservation District", abbr: "WBCD" },
  { name: "Wellsville", abbr: "WEL" },
  { name: "West Jordan", abbr: "WJ" },
  { name: "West Mountain Partners", abbr: "WMP" },
  { name: "White Hills", abbr: "WH" },
  { name: "Wilson Irrigation", abbr: "WI" },
  { name: "Windstream", abbr: "WIN" },
  { name: "Xcel Energy", abbr: "XCEL" },
  { name: "Zayo Group", abbr: "ZAYO" },
];

const Abbrevs = () => {
  const [selectedEntity, setSelectedEntity] = useState('');

  const handleChange = (event) => {
    setSelectedEntity(event.target.value);
  };

  return (
    <div style={{ paddingLeft: '50px' }}>
      <h2 className='text-light'>Search Utility Abbreviations</h2>
      <select
        value={selectedEntity}
        onChange={handleChange}
        style={{ width: '300px', padding: '5px', backgroundColor:'rgb(128, 56, 56)' }}
      >
        <option value="" disabled>
          -- Select an Entity --
        </option>
        {entities.map((entity, index) => (
          <option key={index} value={entity.abbr}>
            {`${entity.name} (${entity.abbr})`}
          </option>
        ))}
      </select>
      {selectedEntity && (
        <p className='text-light' style={{ marginTop: '10px' }}>
          You selected: {entities.find((e) => e.abbr === selectedEntity)?.name} ({selectedEntity})
        </p>
      )}
    </div>
  );
};

export default Abbrevs;